<?php

function TitoConnection($targ){
  $username = "rl";
  $password = "";
  // Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/

  $headers = array();
  $headers[] = "Authorization: Token token=WoKt-Qdq6yfVq1xRt-Eo";
  $headers[] = "Accept: application/vnd.api+json";
  $headers[] = "Content-Type: application/json";

  $ch = curl_init();
  //echo $tar;

  curl_setopt($ch, CURLOPT_URL, "https://api.tito.io/v2/nodeforum/node17/".$targ);
  curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);

  //(curl_setopt($ch, CURLOPT_CUSTOMREQUEST, "GET");
  curl_setopt($ch, CURLOPT_HEADER, false);
  curl_setopt($ch, CURLOPT_POST, false);
  curl_setopt($ch, CURLOPT_NOSIGNAL, 1);
  curl_setopt($ch, CURLOPT_USERPWD, "$username:$password");
  curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);
  curl_setopt($ch, CURLOPT_SSL_VERIFYHOST, 0);
  curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, 0);

  $response = curl_exec($ch);
  $err_status = curl_error($ch);
  $info = curl_getinfo($ch);

    if (curl_error($ch)) {
        echo '<h4>Error :</h4>';
        echo 'Error:' . curl_error($ch)."<br / >";
    }

  $apiresponse = json_decode($response, TRUE);
  curl_close($ch);
  return  $apiresponse;
  }


    function CConnection($targ){
      $username = "rl";
      $password = "";
      // Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/

      $headers = array();
      $headers[] = "Authorization: Token token=WoKt-Qdq6yfVq1xRt-Eo";
      $headers[] = "Accept: application/vnd.api+json";
      $headers[] = "Content-Type: application/json";

      $ch = curl_init();
      //echo $tar;

      curl_setopt($ch, CURLOPT_URL, $targ);
      curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);

      //(curl_setopt($ch, CURLOPT_CUSTOMREQUEST, "GET");
      curl_setopt($ch, CURLOPT_HEADER, false);
      curl_setopt($ch, CURLOPT_POST, false);

      curl_setopt($ch, CURLOPT_USERPWD, "$username:$password");
      curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);
      curl_setopt($ch, CURLOPT_SSL_VERIFYHOST, 0);
      curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, 0);

      $response = curl_exec($ch);
      $err_status = curl_error($ch);
      $info = curl_getinfo($ch);

        if (curl_error($ch)) {
            echo '<h4>Error :</h4>';
            echo 'Error:' . curl_error($ch)."<br / >";
        }

          $apiresponse = json_decode($response, TRUE);
          curl_close($ch);
          return  $apiresponse;
      }


  ?>
